Ch setup database
atlp-rwanda/ecommerce-app-legends-bn pull request #10
Opened 2023-03-02 11:32 UTC by BenoitIT

## Postgres  database setup
#### set up connection between node js application and postgres database so that app can access and send data to postgress database

### What does this PR do?
This has functions and methods to set up connection  [ecommerce-app-legends-bn](https://github.com/atlp-rwanda/ecommerce-app-legends-bn) App with postgres database during development phase.

#### what are the nature of PL contents?
---config folder which has js file with db connection configurations
---models folder which has User model created for functionality testing as well index.js which has db connection with 
     models
---migration folder which store table structures to be migrated to the database
---scripts to run both create migration events as well as make: db migrate
---connection folder which has folder to notify the the status of connection from the node js console

N.B : migrations and models folder are still in progress as new and more migrations and modls will b created

### Description of Tasks completed
----database connection set-up successfully
----first model created successfully
----first migration created and migrated successfully
--- make model and create migration as well as migrate scripts added and tested
### how to test this?
clone repo , branch git clone https://github.com/atlp-rwanda/ecommerce-app-legends-bn.git
-`run npm i`
-have `postgres database` installed 
-create a database with `ecommerce_db`as its name
-create .env file
-under .env file initialize:`DEV_DATABASE_URL=postgres://<username>:<password>@127.0.0.1:5432/ecommerce_db`
###### remember to take away angled bracket  beside username and password as well colon between those two from connection string above
-start the app and check connectivity in development `npm run dev `
-  run `npm run make:migration`  in terminal to make migation  to create new migration
-rename created migration file with your desired file
- run`npm run migrate` to create new table in database
-  run`npm run generate:seed` to create new database seed 
- run`npm run db:seed` to seed the database
-  run`npm run migrate:undo` to revert migrations
<img width="477" alt="Screen Shot 2023-03-02 at 10 57 22" src="https://user-images.githubusercontent.com/103331579/222380479-0ea90ced-3909-429b-a3a5-5da2b9f61f54.png">
 database seed

2023-03-02 16:49 UTC, Aimeana100 approved these changes

2023-03-02 17:31 UTC, ngoma3 approved these changes

2023-03-02 19:50 UTC, Aimeana100 requested changes
Sorry 😔, I tested the codes locally, but not noticed that I had conflicts. @BenoitIT  still have to resolve the issues.

2023-03-03 05:03 UTC, mansurissa requested changes
Resolve conflicts and work on the comments

2023-03-03 05:03 UTC, mansurissa commented on src/docs/index.js
> +const { Router } = require('express');
here use es6 please

2023-03-03 08:04 UTC, FabCode67 approved these changes

2023-03-03 08:11 UTC, mansurissa approved these changes
Looks good now

2023-03-03 08:20 UTC, Aimeana100 approved these changes
Okay, now. It works as expected.

2023-03-03 09:09 UTC, FabCode67 commented
you need to update readme and remove unwanted schemas

2023-03-03 09:43 UTC, FabCode67 approved these changes

2023-03-03 09:43 UTC, ngoma3 approved these changes

2023-03-03 11:38 UTC, Kevin-ishimwe approved these changes
great work !

2023-03-03 13:21 UTC, mansurissa approved these changes

2023-03-03 13:22 UTC, merged