feat[disable-enable-account-#14]
atlp-rwanda/ecommerce-app-legends-bn pull request #45
Opened 2023-03-21 23:20 UTC by FabCode67

# task discription:
Due to varying reasons e.g fraud, abuse, malicious use or violation of terms of service, admin should be able to diable any user account.

GIVEN admin and multiple users exists on the sytem WHEN a user is suspected or proved to have violated the terms of service of the application THEN admin is able to trigger an action to block usage of a particular account and an email sent to the user with reasons fro the block.

# what PR do:

- logged in user can disable an account
- only signed in admin have permision to disable any user's acount
- only signed in admin has permision to inable disabled acount
- if user already enabled or disable will be notfied to an admin
- user will be disbled by assigning him status of inactive
- user will be enabled by assigning him status of active

# how to test it:
- git clone from branch
- npm run dev
- in your browser search localhost:{port}/docs

feat[finish disable-enable-account-#14]

2023-03-22 06:52 UTC, mukunzidd requested changes
- Please read this https://github.com/atlp-rwanda/engineering-playbook/wiki/3.-Pull-Request and base on it to adjust your PR title. Look at the example and adjust to match.
- Look at the commit message formatting. Your commit should not look like the PR description.
- Fix hound issues by following my comment on the hound bot comment.

2023-03-22 06:52 UTC, mukunzidd commented on src/controllers/Auth/user_status.js
> +import  { user } from "../../models";
@FabCode67 the` .hound.yml` is not referencing the aslant config correctly. It says `.eslintrc` while it's `.eslintrc.js`. Update that and below the config_file key add: 

`exclude: ["node_modules/**"]`

2023-03-22 16:36 UTC, FabCode67 commented
> * Please read this https://github.com/atlp-rwanda/engineering-playbook/wiki/3.-Pull-Request and base on it to adjust your PR title. Look at the example and adjust to match.
> * Look at the commit message formatting. Your commit should not look like the PR description.
> * Fix hound issues by following my comment on the hound bot comment.

I did it but when i try to rename the branch using command `git branch -m old_name new_name` and push it it creates the new branch with new name instead of updating the current branch , that is why i created other PR.

I Updated .hound.yml as you recommended me and I have used the resources to write standard pr and commit message.

2023-03-24 06:35 UTC, mansurissa commented
@FabCode67  if this PR is a duplicate. Can you close it?

2023-03-24 06:48 UTC, FabCode67 commented
> @FabCode67 if this PR is a duplicate. Can you close it?

yea sure

2023-03-24 06:49 UTC, closed without merging