feat : Implement seller product creation functionality
atlp-rwanda/ecommerce-app-legends-bn pull request #46
Opened 2023-03-22 13:48 UTC by Aimeana100

#a21b3747e94bbcc55a0c5785601f19f99bf56e6b This commit adds a new product to the vendor's collection

This commit includes the following changes:

-  created 4 models `category`, `product`, `productAttribute` and `productImage`
-  created the routes to CRUD categories that should be accessed by admin only
-  created the routes to add new product *only vendor will add product in his / her own collection *
-  created the routes to add product attributes and images as well in approprite model
-  handle responses accordingly
-  create swagger doc for the routes

## How to test 

1. Clone the project from branch `ft-create-new-product`
2.  Copy `.env.example` to `.env` and fill the variable with actual and real values accordingly 
3.  || in case you run docker   do `docker compose up ` on project root directory or 
4. Run `npm i` to install the dependancy
5. Run `npm run dev` to start the server
6. Open Local IP or localhost in browser at port the server started to `ie : 5000` or 4000
7. Test the app using swangger  
8. registe as an admin, create categories , .. 
9. . create a user vendor and login again as vendor
10. .  create a product , ...

2023-03-22 13:56 UTC, Evaristekanova approved these changes
@BenoitIT  and @Aimeana100  resolve conflicts in readme file

2023-03-22 13:57 UTC, Evaristekanova requested changes
resolve conflict from readme file

2023-03-23 16:58 UTC, BenoitIT approved these changes

2023-03-23 16:58 UTC, FabCode67 approved these changes

2023-03-23 17:14 UTC, Kevin-ishimwe approved these changes
great work

2023-03-23 17:24 UTC, mansurissa approved these changes
Merging this to unblock others but make sure you write test for everything

2023-03-23 17:24 UTC, mansurissa commented on jest.config.js
> +    "!src/controllers/products/categoryController.js",
Create issues to test all testable files here

2023-03-23 17:24 UTC, merged

2023-03-24 08:36 UTC, Aimeana100 commented
![](https://github.trello.services/images/mini-trello-icon.png) [A seller should be able to Create/Add a product](https://trello.com/c/8VAiMVMC/15-a-seller-should-be-able-to-create-add-a-product)