feat[ft-search-product]
atlp-rwanda/ecommerce-app-legends-bn pull request #56
Opened 2023-03-25 22:13 UTC by ngoma3

### What does this PR do

-  allow user to search product
-   write its swagger documentation
### How to run it

- git clone from repo
- git checkout ft-search-product
- set .env as shown in .envexample
-  run npm i
-  run npm run dev
-  copy this url in your postman: http://localhost:{port}/api/v1/product
-  you will add query keywords on this GET url `ex`: http://localhost:{port}/api/v1/product?q=apple
-  the api will search for the alike content in the product collection depending on name,description and model
-  it will respond the arrayList with all matched products.

2023-03-26 09:02 UTC, Kevin-ishimwe approved these changes

2023-03-26 09:02 UTC, Kevin-ishimwe commented on src/controllers/products/productController.js
> +  console.log("this is where the error should occur",q);
and this one to

2023-03-26 09:02 UTC, Kevin-ishimwe commented on src/controllers/products/productController.js
> +  console.log("this is where the error should");
if possible could we remove these console.log()

2023-03-26 09:30 UTC, Evaristekanova requested changes, later dismissed
@ngoma3 try to remove try and catch and use the reusable function to handle that and work on the way you are sending responses cz you are not sending status try to use jsend response

2023-03-26 19:21 UTC, Christa22 reviewed
I think You should  have proper status message

2023-03-26 19:22 UTC, BenoitIT commented
There is a conflict on your PR in reademe

2023-03-27 08:09 UTC, FabCode67 approved these changes
Good job @ngoma3

2023-03-27 08:09 UTC, FabCode67 commented on src/controllers/products/productController.js
> +  return res.send({status: req.t('success'), itemsList: items});
add status code here?

2023-03-27 08:09 UTC, FabCode67 commented on src/controllers/products/productController.js
> +} catch (err) {
remove this catch block  by importing asyncWrapper middleware

2023-03-27 08:28 UTC, BenoitIT approved these changes

2023-03-27 08:47 UTC, Aimeana100 approved these changes
Good job @ngoma3

2023-03-27 09:15 UTC, mansurissa approved these changes
LGTM

2023-03-27 09:16 UTC, merged