Ft order status 31
atlp-rwanda/ecommerce-app-legends-bn pull request #86
Opened 2023-04-15 22:34 UTC by Kevin-ishimwe

#### What does this PR do?
adds order status tracking capabilities to backend
#### Description of Task to be completed?
-endpoint for getting order status 
-endpoint for updating order status
-websocket event listener 

#### How should this be manually tested?
open the repository documentation 
on `localhost:4000/docs` and test under the 
Order Details section

2023-04-16 18:16 UTC, FabCode67 requested changes

2023-04-16 18:16 UTC, FabCode67 commented on src/controllers/order/orderStatusController.js
> +  res.json({ status: req.t('success'), message: req.t('status_order') });
add status code on response

2023-04-16 18:16 UTC, FabCode67 commented on src/controllers/order/orderStatusController.js
> +  res.json({ status: req.t('success'), order: order });
what status code here?

2023-04-16 18:16 UTC, FabCode67 commented on src/controllers/order/orderStatusController.js
> +  const order = await db.Order.findOne({ where: { userId: req.user.id } });
what can happen if order is not found?

2023-04-16 18:27 UTC, FabCode67 requested changes

2023-04-16 18:27 UTC, FabCode67 commented on src/locales/fr/translation.json
> +  "product_does_not_exist_in_collection": "Product doesn't exist in your collection",
translate this line as expected

2023-04-16 21:13 UTC, Evaristekanova requested changes
you didn't specify status codes for the returned responses and i see your french transilation are still in English

2023-04-17 00:12 UTC, Kevin-ishimwe commented on src/controllers/order/orderStatusController.js
> +  const order = await db.Order.findOne({ where: { userId: req.user.id } });
it returns an empty array

2023-04-17 00:14 UTC, Kevin-ishimwe commented on src/locales/fr/translation.json
> +  "product_does_not_exist_in_collection": "Product doesn't exist in your collection",
this isnt in my work

2023-04-17 12:57 UTC, FabCode67 approved these changes

2023-04-18 19:10 UTC, BenoitIT approved these changes

2023-04-22 16:47 UTC, Evaristekanova approved these changes

2023-05-16 15:13 UTC, merged